#ifndef SSEQ_H
#define SSEQ_H

#define SSEQ_COMMAND_NUM_TRACKS 0xFE
#define SSEQ_COMMAND_TRACK_ADDRESS 0x93
#define SSEQ_COMMAND_WAIT 0x80
#define SSEQ_COMMAND_BANK 0x81
#define SSEQ_COMMAND_JUMP 0x94
#define SSEQ_COMMAND_CALL 0x95
#define SSEQ_COMMAND_RETURN 0xFD
#define SSEQ_COMMAND_RANDOM 0xA0
#define SSEQ_COMMAND_VARIABLE 0xA1
#define SSEQ_COMMAND_IF 0xA2
#define SSEQ_COMMAND_SET 0xB0
#define SSEQ_COMMAND_ADD 0xB1
#define SSEQ_COMMAND_SUBTRACT 0xB2
#define SSEQ_COMMAND_MULTIPLY 0xB3
#define SSEQ_COMMAND_DIVIDE 0xB4
#define SSEQ_COMMAND_SHIFT 0xB5
#define SSEQ_COMMAND_RANDOM_NOTE 0xB6
#define SSEQ_COMMAND_COMPARE_EQUAL 0xB8
#define SSEQ_COMMAND_COMPARE_GEQUAL 0xB9
#define SSEQ_COMMAND_COMPARE_GREATER 0xBA
#define SSEQ_COMMAND_COMPARE_LEQUAL 0xBB
#define SSEQ_COMMAND_COMPARE_LESS 0xBC
#define SSEQ_COMMAND_COMPARE_NEQUAL 0xBD
#define SSEQ_COMMAND_PAN 0xC0
#define SSEQ_COMMAND_VOLUME 0xC1
#define SSEQ_COMMAND_MASTER_VOLUME 0xC2
#define SSEQ_COMMAND_TRANSPOSE 0xC3
#define SSEQ_COMMAND_PITCH_BEND 0xC4
#define SSEQ_COMMAND_PITCH_BEND_RANGE 0xC5
#define SSEQ_COMMAND_PRIORITY 0xC6
#define SSEQ_COMMAND_MONO_NOTE 0xC7 // note wait
#define SSEQ_COMMAND_TIE 0xC8
#define SSEQ_COMMAND_PORTAMENTO_CONTROL 0xC9
#define SSEQ_COMMAND_MODULATION_DEPTH 0xCA
#define SSEQ_COMMAND_MODULATION_SPEED 0xCB
#define SSEQ_COMMAND_MODULATION_TYPE 0xCC
#define SSEQ_COMMAND_MODULATION_RANGE 0xCD
#define SSEQ_COMMAND_PORTAMENTO_ON 0xCE
#define SSEQ_COMMAND_PORTAMENTO_TIME 0xCF
#define SSEQ_COMMAND_ATTACK_RATE 0xD0
#define SSEQ_COMMAND_DECAY_RATE 0xD1
#define SSEQ_COMMAND_SUSTAIN_RATE 0xD2
#define SSEQ_COMMAND_RELEASE_RATE 0xD3
#define SSEQ_COMMAND_LOOP_START 0xD4
#define SSEQ_COMMAND_LOOP_END 0xFC
#define SSEQ_COMMAND_VOLUME_2 0xD5
#define SSEQ_COMMAND_PRINT_VARIABLE 0xD6
#define SSEQ_COMMAND_MODULATION_DELAY 0xE0
#define SSEQ_COMMAND_TEMPO 0xE1
#define SSEQ_COMMAND_SWEEP_PITCH 0xE3
#define SSEQ_COMMAND_END 0xFF

void ReadSseq(char *inputPath, char *outputPath);

#endif //SSEQ_H